/**
 * Standardized Error Codes
 * These codes are language-agnostic and should be translated in the Flutter app
 */
export enum ErrorCode {
  // ============================================
  // AUTHENTICATION & AUTHORIZATION (1000-1999)
  // ============================================

  // General Auth Errors (1000-1099)
  UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  FORBIDDEN = "AUTH_FORBIDDEN",
  INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",
  INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS",
  INVALID_API_KEY = "AUTH_INVALID_API_KEY",

  // Registration Errors (1100-1199)
  EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  INVALID_EMAIL_FORMAT = "AUTH_INVALID_EMAIL_FORMAT",
  WEAK_PASSWORD = "AUTH_WEAK_PASSWORD",
  PASSWORDS_DO_NOT_MATCH = "AUTH_PASSWORDS_DO_NOT_MATCH",
  REGISTRATION_FAILED = "AUTH_REGISTRATION_FAILED",

  // Email Verification (1200-1299)
  EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_VERIFIED = "AUTH_EMAIL_ALREADY_VERIFIED",
  VERIFICATION_TOKEN_INVALID = "AUTH_VERIFICATION_TOKEN_INVALID",
  VERIFICATION_TOKEN_EXPIRED = "AUTH_VERIFICATION_TOKEN_EXPIRED",

  // Magic Link (1300-1399)
  MAGIC_LINK_INVALID = "AUTH_MAGIC_LINK_INVALID",
  MAGIC_LINK_EXPIRED = "AUTH_MAGIC_LINK_EXPIRED",
  MAGIC_LINK_ALREADY_USED = "AUTH_MAGIC_LINK_ALREADY_USED",
  MAGIC_LINK_NOT_FOUND = "AUTH_MAGIC_LINK_NOT_FOUND",

  // ============================================
  // USER MANAGEMENT (2000-2999)
  // ============================================
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_DELETED = "USER_DELETED",
  USER_UPDATE_FAILED = "USER_UPDATE_FAILED",
  USER_DELETE_FAILED = "USER_DELETE_FAILED",

  // ============================================
  // CIRCLES (3000-3999)
  // ============================================

  // Circle Errors (3000-3099)
  CIRCLE_NOT_FOUND = "CIRCLE_NOT_FOUND",
  CIRCLE_ALREADY_EXISTS = "CIRCLE_ALREADY_EXISTS",
  CIRCLE_CREATE_FAILED = "CIRCLE_CREATE_FAILED",
  CIRCLE_UPDATE_FAILED = "CIRCLE_UPDATE_FAILED",
  CIRCLE_DELETE_FAILED = "CIRCLE_DELETE_FAILED",
  CIRCLE_NAME_REQUIRED = "CIRCLE_NAME_REQUIRED",
  CIRCLE_INVALID_PRIVACY = "CIRCLE_INVALID_PRIVACY",

  // Circle Member Errors (3100-3199)
  NOT_CIRCLE_MEMBER = "CIRCLE_NOT_MEMBER",
  NOT_CIRCLE_OWNER = "CIRCLE_NOT_OWNER",
  ALREADY_CIRCLE_MEMBER = "CIRCLE_ALREADY_MEMBER",
  CIRCLE_MEMBER_LIMIT_REACHED = "CIRCLE_MEMBER_LIMIT_REACHED",
  CANNOT_REMOVE_CIRCLE_OWNER = "CIRCLE_CANNOT_REMOVE_OWNER",
  MEMBER_ADD_FAILED = "CIRCLE_MEMBER_ADD_FAILED",
  MEMBER_REMOVE_FAILED = "CIRCLE_MEMBER_REMOVE_FAILED",
  MEMBER_UPDATE_FAILED = "CIRCLE_MEMBER_UPDATE_FAILED",
  CIRCLE_MEMBER_PERMISSION_DENIED = "CIRCLE_MEMBER_PERMISSION_DENIED",
  CIRCLE_MEMBER_ALREADY_EXISTS = "CIRCLE_MEMBER_ALREADY_EXISTS",

  // Circle Invitation Errors (3200-3299)
  INVITATION_NOT_FOUND = "CIRCLE_INVITATION_NOT_FOUND",
  INVITATION_EXPIRED = "CIRCLE_INVITATION_EXPIRED",
  INVITATION_ALREADY_ACCEPTED = "CIRCLE_INVITATION_ALREADY_ACCEPTED",
  INVITATION_ALREADY_DECLINED = "CIRCLE_INVITATION_ALREADY_DECLINED",
  INVITATION_EMAIL_MISMATCH = "CIRCLE_INVITATION_EMAIL_MISMATCH",
  INVITATION_LIMIT_REACHED = "CIRCLE_INVITATION_LIMIT_REACHED",
  INVITATION_ALREADY_EXISTS = "CIRCLE_INVITATION_ALREADY_EXISTS",
  INVITATION_CREATE_FAILED = "CIRCLE_INVITATION_CREATE_FAILED",
  INVITATION_SEND_FAILED = "CIRCLE_INVITATION_SEND_FAILED",

  // ============================================
  // EVENTS (4000-4999)
  // ============================================

  // Event Errors (4000-4099)
  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
  EVENT_CREATE_FAILED = "EVENT_CREATE_FAILED",
  EVENT_UPDATE_FAILED = "EVENT_UPDATE_FAILED",
  EVENT_DELETE_FAILED = "EVENT_DELETE_FAILED",
  EVENT_TITLE_REQUIRED = "EVENT_TITLE_REQUIRED",
  EVENT_INVALID_STATUS = "EVENT_INVALID_STATUS",

  // Event Lock/Finalize (4100-4199)
  EVENT_ALREADY_LOCKED = "EVENT_ALREADY_LOCKED",
  EVENT_NOT_LOCKED = "EVENT_NOT_LOCKED",
  EVENT_ALREADY_FINALIZED = "EVENT_ALREADY_FINALIZED",
  EVENT_NOT_FINALIZED = "EVENT_NOT_FINALIZED",
  EVENT_CANNOT_MODIFY_LOCKED = "EVENT_CANNOT_MODIFY_LOCKED",
  EVENT_CANNOT_MODIFY_FINALIZED = "EVENT_CANNOT_MODIFY_FINALIZED",
  EVENT_LOCK_FAILED = "EVENT_LOCK_FAILED",
  EVENT_FINALIZE_FAILED = "EVENT_FINALIZE_FAILED",

  // Event Time (4200-4299)
  EVENT_TIME_NOT_FOUND = "EVENT_TIME_NOT_FOUND",
  EVENT_TIME_REQUIRED = "EVENT_TIME_REQUIRED",
  EVENT_TIME_INVALID = "EVENT_TIME_INVALID",
  EVENT_TIME_CONFLICT = "EVENT_TIME_CONFLICT",
  EVENT_NO_TIMES_AVAILABLE = "EVENT_NO_TIMES_AVAILABLE",

  // RSVP (4300-4399)
  RSVP_NOT_FOUND = "EVENT_RSVP_NOT_FOUND",
  RSVP_UPDATE_FAILED = "EVENT_RSVP_UPDATE_FAILED",
  RSVP_INVALID_STATUS = "EVENT_RSVP_INVALID_STATUS",
  RSVP_ALREADY_EXISTS = "EVENT_RSVP_ALREADY_EXISTS",

  // Voting (4400-4499)
  VOTE_NOT_FOUND = "EVENT_VOTE_NOT_FOUND",
  VOTE_FAILED = "EVENT_VOTE_FAILED",
  CANNOT_VOTE_LOCKED_EVENT = "EVENT_CANNOT_VOTE_LOCKED",
  ALREADY_VOTED = "EVENT_ALREADY_VOTED",

  // ============================================
  // PERSONAL CALENDAR (4500-4599)
  // ============================================
  PERSONAL_EVENT_NOT_FOUND = "PERSONAL_EVENT_NOT_FOUND",
  PERSONAL_EVENT_CREATE_FAILED = "PERSONAL_EVENT_CREATE_FAILED",
  PERSONAL_EVENT_UPDATE_FAILED = "PERSONAL_EVENT_UPDATE_FAILED",
  PERSONAL_EVENT_DELETE_FAILED = "PERSONAL_EVENT_DELETE_FAILED",
  PERSONAL_EVENT_TIME_CONFLICT = "PERSONAL_EVENT_TIME_CONFLICT",
  PERSONAL_EVENT_INVALID_TIME = "PERSONAL_EVENT_INVALID_TIME",

  // ============================================
  // VALIDATION ERRORS (5000-5999)
  // ============================================
  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_INPUT = "VALIDATION_INVALID_INPUT",
  REQUIRED_FIELD_MISSING = "VALIDATION_REQUIRED_FIELD_MISSING",
  INVALID_FORMAT = "VALIDATION_INVALID_FORMAT",
  INVALID_UUID = "VALIDATION_INVALID_UUID",
  INVALID_DATE = "VALIDATION_INVALID_DATE",
  INVALID_EMAIL = "VALIDATION_INVALID_EMAIL",
  INVALID_URL = "VALIDATION_INVALID_URL",
  VALUE_TOO_LONG = "VALIDATION_VALUE_TOO_LONG",
  VALUE_TOO_SHORT = "VALIDATION_VALUE_TOO_SHORT",
  VALUE_OUT_OF_RANGE = "VALIDATION_VALUE_OUT_OF_RANGE",

  // ============================================
  // NOTIFICATIONS (5000-5999)
  // ============================================
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_SEND_FAILED = "NOTIFICATION_SEND_FAILED",
  DEVICE_TOKEN_INVALID = "DEVICE_TOKEN_INVALID",
  OUTBOX_PROCESSING_FAILED = "OUTBOX_PROCESSING_FAILED",
  NOTIFICATION_ACCESS_DENIED = "NOTIFICATION_ACCESS_DENIED",

  // ============================================
  // DATABASE & SYSTEM ERRORS (6000-6999)
  // ============================================
  DATABASE_ERROR = "DB_ERROR",
  DATABASE_CONNECTION_FAILED = "DB_CONNECTION_FAILED",
  DUPLICATE_ENTRY = "DB_DUPLICATE_ENTRY",
  FOREIGN_KEY_CONSTRAINT = "DB_FOREIGN_KEY_CONSTRAINT",
  TRANSACTION_FAILED = "DB_TRANSACTION_FAILED",
  QUERY_FAILED = "DB_QUERY_FAILED",

  // ============================================
  // GENERIC ERRORS (7000-7999)
  // ============================================
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  NOT_FOUND = "NOT_FOUND",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",

  // ============================================
  // EXTERNAL SERVICE ERRORS (8000-8999)
  // ============================================
  EMAIL_SERVICE_ERROR = "EMAIL_SERVICE_ERROR",
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",
  STORAGE_SERVICE_ERROR = "STORAGE_SERVICE_ERROR",
  EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR",
}

/**
 * Standardized Error Response Structure
 */
export interface ErrorResponse {
  success: false;
  errorCode: ErrorCode;
  message: string;
  details?: any; // Optional debugging info (always included for transparency)
  timestamp?: string;
  path?: string;
}

/**
 * Success Response Structure
 */
export interface SuccessResponse<T = any> {
  success: true;
  data: T;
}

/**
 * Generic API Response
 */
export type ApiResponse<T = any> = SuccessResponse<T> | ErrorResponse;
